#ifndef DEF_NOTIFICATIONDATAROLES_H
#define DEF_NOTIFICATIONDATAROLES_H

enum NotificationDataRoles {
	NDR_ICON,
	NDR_TOOLTIP,
	NDR_STREAM_JID,
	NDR_CONTACT_JID,
	NDR_ROSTER_NOTIFY_ORDER,
	NDR_POPUP_IMAGE,
	NDR_POPUP_CAPTION,
	NDR_POPUP_TITLE,
	NDR_POPUP_HTML,
	NDR_POPUP_TIMEOUT,
	NDR_SOUND_FILE
};

#endif // DEF_NOTIFICATIONDATAROLES_H
