#ifndef ACTIONGROUPS_INC
#define ACTIONGROUPS_INC

#define STATUSMENU_ACTION_GROUP_STREAM                190
#define STATUSMENU_ACTION_GROUP_MAIN                  200
#define SETTINGS_ACTION_GROUP_OPTIONS                 700
#define ROSTERCHANGER_ACTION_GROUP_SUBSCRIPTION       790
#define ROSTERCHANGER_ACTION_GROUP                    800
#define MAINWINDOW_ACTION_GROUP_QUIT                  1000

#endif