#ifndef ROSTERLABELORDERS_H
#define ROSTERLABELORDERS_H

#define NULL_LABEL_ID -1
#define DISPLAY_LABEL_ID 0

#define DECORATION_LABEL_ORDER -1024
#define STREAMCONNECTING_LABEL_ORDER -1000
#define MESSAGE_LABEL_ORDER -700
#define ROSTERCHANGER_LABEL_ORDER -500
#define DISPLAY_LABEL_ORDER 0
#define RIGHTALIGN_LABEL_ORDER 1024

#endif