TEMPLATE = subdirs

SUBDIRS = optionsmanager \
          xmppstreams \
          iqauth \
          saslauth \
          stanzaprocessor \
          roster \
          presence \
          rostersmodel \
          mainwindow \
          rostersview \
          statuschanger \
          rosterchanger \
          accountmanager \
          traymanager \
          privatestorage \
          messageprocessor \
          messagewidgets \
          messagestyles \
          adiummessagestyle \
          simplemessagestyle \
          normalmessagehandler \
          chatmessagehandler \
          compress \
          connectionmanager \
          defaultconnection \
          starttls \
          statusicons \
          skinmanager \
          emoticons \
          clientinfo \
          vcard \
          multiuserchat \
          dataforms \
          servicediscovery \
          bookmarks \
          registration \
          commands \
          jabbersearch \
          gateways \
          messagearchiver \
          privacylists \
          sessionnegotiation \
          avatars \
          notifications \
          autostatus \
          rostersearch \
          console \
          annotations \
          chatstates \
          datastreamsmanager \
          filestreamsmanager \
          filetransfer \
          inbandstreams \
          socksstreams \
          captchaforms \
          bitsofbinary \
          xmppuriqueries
