#ifndef DEF_ROSTEREDITHANDLERORDERS_H
#define DEF_ROSTEREDITHANDLERORDERS_H

#define REHO_BOOKMARKS_RENAME              500
#define REHO_ROSTERCHANGER_RENAME          500

#endif //DEF_ROSTEREDITHANDLERORDERS_H
