#ifndef DEF_MESSAGEEDITCONTENTSHANDLERORDERS_H
#define DEF_MESSAGEEDITCONTENTSHANDLERORDERS_H

#define MECHO_MESSAGEWIDGETS_COPY_INSERT                     100
#define MECHO_EMOTICONS_CONVERT_IMAGE2TEXT                   500

#endif // DEF_MESSAGEEDITCONTENTSHANDLERORDERS_H
