set(SOURCES "action.cpp"
			"advanceditem.cpp"
			"advanceditemdelegate.cpp"
			"advanceditemmodel.cpp"
			"animatedtextbrowser.cpp"
			"boxwidget.cpp"
			"closebutton.cpp"
			"datetime.cpp"
			"filecookiejar.cpp"
			"filestorage.cpp"
			"iconsetdelegate.cpp"
			"iconstorage.cpp"
			"imagemanager.cpp"
			"jid.cpp"
			"menu.cpp"
			"menubarchanger.cpp"
			"message.cpp"
			"options.cpp"
			"ringbuffer.cpp"
			"searchlineedit.cpp"
			"shortcuts.cpp"
			"stanza.cpp"
			"statusbarchanger.cpp"
			"systemmanager.cpp"
			"textmanager.cpp"
			"toolbarchanger.cpp"
			"unzipfile.cpp"
			"versionparser.cpp"
			"widgetmanager.cpp"
			"xmpperror.cpp")

if (UNIX AND NOT APPLE)
	set(SOURCES ${SOURCES} "x11info.cpp")
endif (UNIX AND NOT APPLE)

set(HEADERS "action.h"
            "filestorage.h"
            "iconstorage.h"
            "menu.h"
            "menubarchanger.h"
            "options.h"
            "shortcuts.h"
            "statusbarchanger.h"
            "systemmanager.h"
            "toolbarchanger.h"
            "animatedtextbrowser.h"
            "closebutton.h"
            "searchlineedit.h"
            "imagemanager.h"
            "advanceditem.h"
            "advanceditemmodel.h"
            "advanceditemdelegate.h"
            "filecookiejar.h"
            "boxwidget.h")

qt5_wrap_cpp(MOC_SOURCES ${HEADERS})
