#ifndef DEF_NOTIFICATIONDATAROLES_H
#define DEF_NOTIFICATIONDATAROLES_H

enum NotificationDataRoles {
  NDR_ICON,
  NDR_TOOLTIP,
  NDR_ROSTER_STREAM_JID,
  NDR_ROSTER_CONTACT_JID,
  NDR_ROSTER_NOTIFY_ORDER,
  NDR_WINDOW_IMAGE,
  NDR_WINDOW_CAPTION,
  NDR_WINDOW_TITLE,
  NDR_WINDOW_TEXT,
  NDR_WINDOW_TIMEOUT,
  NDR_SOUND_FILE
};

#endif
