#ifndef DEF_XMPPSTANZAHANDLERORDERS_H
#define DEF_XMPPSTANZAHANDLERORDERS_H

#define XSHO_STANZAPROCESSOR        300
#define XSHO_XMPP_STREAM            500
#define XSHO_SASL_VERSION           700
#define XSHO_XMPP_FEATURE           900
#define XSHO_CONSOLE                1000

#endif //DEF_XMPPSTANZAHANDLERORDERS_H
