#ifndef DEF_ROSTERCLICKHOOKERORDERS_H
#define DEF_ROSTERCLICKHOOKERORDERS_H

#define RCHO_ROSTERSEARCH                   100
#define RCHO_METACONTACTS                   500
#define RCHO_RECENTCONTACTS                 500
#define RCHO_MULTIUSERCHAT                  1000
#define RCHO_SERVICEDISCOVERY               1000
#define RCHO_CHATMESSAGEHANDLER             1000
#define RCHO_NORMALMESSAGEHANDLER           1500

#endif // DEF_ROSTERCLICKHOOKERORDERS_H
