#ifndef DEF_EDITCONTENTSHANDLERORDERS_H
#define DEF_EDITCONTENTSHANDLERORDERS_H

#define ECHO_MESSAGEWIDGETS_COPY_INSERT                     100
#define ECHO_EMOTICONS_CONVERT_IMAGE2TEXT                   500

#endif // DEF_EDITCONTENTSHANDLERORDERS_H
