#ifndef DEF_MESSAGEVIEWURLHANDLERORDERS_H
#define DEF_MESSAGEVIEWURLHANDLERORDERS_H

#define MVUHO_FILETRANSFER                     300
#define MVUHO_MULTIUSERCHAT                    500
#define MVUHO_XMPPURIQUERIES                   500
#define MVUHO_MESSAGEWIDGETS_DEFAULT           1000

#endif // DEF_MESSAGEVIEWURLHANDLERORDERS_H
