#ifndef DEF_MULTIUSERNOTIFYORDERS_H
#define DEF_MULTIUSERNOTIFYORDERS_H

#define MUNO_PRIVATE_MESSAGE            200
#define MUNO_CHATSTATE_TYPING           900

#endif // DEF_MULTIUSERNOTIFYORDERS_H
