#ifndef DEF_ROSTERDATAHOLDERORDERS_H
#define DEF_ROSTERDATAHOLDERORDERS_H

#define RDHO_ROSTER_NOTIFY          500
#define RDHO_DEFAULT                1000

#endif // DEF_ROSTERDATAHOLDERORDERS_H
