#ifndef DEF_ROSTERPROXYORDERS_H
#define DEF_ROSTERPROXYORDERS_H

#define RPO_ROSTERSEARCH_FILTER           300
#define RPO_METACONTACTS_FILTER           500
#define RPO_ROSTERSVIEW_SORTFILTER        1000

#endif // DEF_ROSTERPROXYORDERS_H
