#ifndef DEF_XMPPSTANZAHANDLERORDERS_H
#define DEF_XMPPSTANZAHANDLERORDERS_H

#define XSHO_STANZAPROCESSOR      100
#define XSHO_XMPPSTREAM           800
#define XSHO_XMPP_FEATURE         900
#define XSHO_CONSOLE              1000

#endif //DEF_XMPPSTANZAHANDLERORDERS_H
