#ifndef DEF_MESSAGEEDITSENDHANDLERORDERS_H 
#define DEF_MESSAGEEDITSENDHANDLERORDERS_H

#define MESHO_MULTIUSERCHATWINDOW_COMMANDS                      500

#define MESHO_CHATMESSAGEHANDLER                                1000
#define MESHO_NORMALMESSAGEHANDLER                              1000
#define MESHO_MULTIUSERCHATWINDOW_GROUPCHAT                     1000
#define MESHO_MULTIUSERCHATWINDOW_PRIVATECHAT                   1001

#endif // DEF_MESSAGEEDITSENDHANDLERORDERS_H
