#ifndef DEF_NOTIFICATIONDATAROLES_H
#define DEF_NOTIFICATIONDATAROLES_H

enum NotificationDataRoles {
	// Common roles
	NDR_ICON,
	NDR_TOOLTIP,
	NDR_STREAM_JID,
	NDR_CONTACT_JID,
	// RosterIcon
	NDR_ROSTER_ORDER,
	// PopupWindow
	NDR_POPUP_IMAGE,
	NDR_POPUP_CAPTION,
	NDR_POPUP_TITLE,
	NDR_POPUP_HTML,
	NDR_POPUP_TIMEOUT,
	// SoundPlay
	NDR_SOUND_FILE,
	// AlertWidget
	NDR_ALERT_WIDGET,
	// TabPageNotify
	NDR_TABPAGE_OBJECT,
	NDR_TABPAGE_PRIORITY,
	NDR_TABPAGE_ICONBLINK
};

#endif // DEF_NOTIFICATIONDATAROLES_H
