#ifndef DEF_TABPAGENOTIFYPRIORITIES_H
#define DEF_TABPAGENOTIFYPRIORITIES_H

#define TPNP_CHATSTATE_TYPING     200
#define TPNP_NEW_MESSAGE          600

#endif // DEF_TABPAGENOTIFYPRIORITIES_H
