#ifndef DEF_ARCHIVEINDEXTYPEROLE_H
#define DEF_ARCHIVEINDEXTYPEROLE_H

enum HistoryWindowItemTypes {
  HIT_INVALID_TYPE,
  HIT_HEADER_JID,
  HIT_HEADER_DATE,
  HIT_HEADER_SUBJECT,
  HIT_GROUP_CONTACT,
  HIT_GROUP_DATE,
  HIT_SORT_ITEM
};

enum HistoryWindowDataRoles {
  HDR_ITEM_TYPE          = 32,
  HDR_STREAM_JID,
  HDR_DATE_START,
  HDR_DATE_END,
  HDR_HEADER_WITH,
  HDR_HEADER_START,
  HDR_HEADER_SUBJECT,
  HDR_HEADER_THREAD,
  HDR_HEADER_VERSION,
  HDR_SORT_ROLE
};

#endif
