#ifndef MULTIUSERDATAROLES_H
#define MULTIUSERDATAROLES_H

#include <QObject>

enum MultiUserDataRoles
{
  MUDR_STREAMJID = Qt::UserRole,
  MUDR_CONTACTJID,
  MUDR_ROOMJID,
  MUDR_REALJID,
  MUDR_NICK_NAME,
  MUDR_ROLE,
  MUDR_AFFILIATION,
  MUDR_SHOW,
  MUDR_STATUS,
  MUDR_VIEW_COLOR,
  MUDR_ROLE_COLOR
};

#endif
