#ifndef DEF_MULTIUSERDATAROLES_H
#define DEF_MULTIUSERDATAROLES_H

enum MultiUserDataRoles {
  MUDR_STREAM_JID = 32,
  MUDR_CONTACT_JID,
  MUDR_ROOM_JID,
  MUDR_REAL_JID,
  MUDR_NICK_NAME,
  MUDR_ROLE,
  MUDR_AFFILIATION,
  MUDR_SHOW,
  MUDR_STATUS,
  MUDR_VIEW_COLOR,
  MUDR_ROLE_COLOR
};

#endif
