#ifndef DEF_XMPPELEMENTHANDLERORDERS_H
#define DEF_XMPPELEMENTHANDLERORDERS_H

#define XEHO_STANZAPROCESSOR      300
#define XEHO_XMPPSTREAM           800
#define XEHO_XMPP_FEATURE         900
#define XEHO_CONSOLE              1000

#endif //DEF_XMPPELEMENTHANDLERORDERS_H
